### ISSUE TITLE
lighting of leds depending on the value of mental commands

### ISSUE THREAD

**Issue by elosman11** [Emotiv/opensoundcontrol#12]
In the demonstration of a video https://www.youtube.com/watch?v=j9XUM6IAPOk&t  I see that the LEDs light up depending on the value in the virtual Bainwear which is from 0 to 1, with the different mental commands, for example in the PUSH mental command with a value less than 0.25 only the first one lights up. led, with a value of 0.5 three leds light up, with a value of 1 all the leds light up.
Could you help me with that part as I do it. I tried your code and if the change of the mental commands seen in the arduino serial monitor works, I use the arduino uno and the ethernet shield

**Comment by hoangphamemotiv** [comment]
Hi @elosman11 
about the video demo, it light up leds following values from PUSH. each value range turn on 1 leb. But because the leb update slow and value changed fast, so you saw it look like at the same time. anyway, that just an idea for using Mental command with Arduino. 
About the example, it doesn't have the lighting part, it only simple receives Emotiv detection value in Arduino via ethernet shield (you can modify it to work with wifi). 
To light up leb, you can assign a specific  value for a leb: > 0.1 turn on leb 1 from port 1, >0.2 turn on leb 2 from port 2...

**Comment by elosman11** [comment]
Can you help me to make it work with wifi???

**Comment by hoangphamemotiv** [comment]
@elosman11 . you may check if your board support Wifi. 
i see there is a library : https://github.com/arduino-libraries/WiFi

**Comment by elosman11** [comment]
It could be implemented with the esp8266 board???
